### ISSUE TITLE
Will you make it as a github action?

### ISSUE THREAD

**Issue by xrdavies** [ShenQingchuan/github-contributor-svg-generator#1]
Will you make it a GitHub action?  We would like to integrate this tool to generate the contributor graph for our community.

**Comment by ShenQingchuan** [comment]
> Will you make it a GitHub action? We would like to integrate this tool to generate the contributor graph for our community.

Sure! I'd like to make it work as a Github Action in this weekend!

**Comment by cfc4n** [comment]
wating for your good news.

**Comment by ShenQingchuan** [comment]
@xrdavies  @cfc4n

Thank you very much for bringing these issues to my attention. I have already upgraded the code in this repository. If you need to use my tool to configure Github Actions, you can refer to the updated README.
