### ISSUE TITLE
Bug: optimize will transform <style> to inlineStyle

### ISSUE THREAD

**Issue by Simon-He95** [ShenQingchuan/github-contributor-svg-generator#5]
before:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/57086651/228745937-b4396b0d-2895-46f3-9e1f-198619c6b54b.png">

after:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/57086651/228745843-dd739d61-8e30-44ec-8d38-bf4a4085f7f5.png">

**Comment by ShenQingchuan** [comment]
@Simon-He95  有点不理解，他居然这里 transform 成为 inline style 
他这样做会有啥好处吗？
或者说首先问 改成 inline style 会导致样式失效吗？

**Comment by Simon-He95** [comment]
就是你写class和inline style的区别，样式不会丢失但是性能上会有点区别
